// flow-typed signature: 3d3b591a70045b907c75badee099443e
// flow-typed version: <<STUB>>/path-browserify_v0.0.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'path-browserify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'path-browserify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'path-browserify/index' {
  declare module.exports: $Exports<'path-browserify'>;
}
declare module 'path-browserify/index.js' {
  declare module.exports: $Exports<'path-browserify'>;
}
