// flow-typed signature: 29df7f8394a664e6b94ae5c07cd5df24
// flow-typed version: <<STUB>>/pokemon_v^1.2.3/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pokemon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pokemon' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'pokemon/index' {
  declare module.exports: $Exports<'pokemon'>;
}
declare module 'pokemon/index.js' {
  declare module.exports: $Exports<'pokemon'>;
}
