// flow-typed signature: 89bcbc995f1d8583c9af3ddcb7b4871b
// flow-typed version: <<STUB>>/punycode_v^1.2.4/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'punycode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'punycode' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'punycode/punycode' {
  declare module.exports: any;
}

// Filename aliases
declare module 'punycode/punycode.js' {
  declare module.exports: $Exports<'punycode/punycode'>;
}
