// flow-typed signature: 7904f156912e5be444907e77fbc367b1
// flow-typed version: <<STUB>>/react-native-os_v^1.0.1/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-os'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-os' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-os/index' {
  declare module.exports: $Exports<'react-native-os'>;
}
declare module 'react-native-os/index.js' {
  declare module.exports: $Exports<'react-native-os'>;
}
