// flow-typed signature: d7abdbe8e545ddb0faefb02ccdb0429c
// flow-typed version: <<STUB>>/react-native-status-bar-height_v^2.1.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-status-bar-height'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-status-bar-height' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-status-bar-height/index' {
  declare module.exports: $Exports<'react-native-status-bar-height'>;
}
declare module 'react-native-status-bar-height/index.js' {
  declare module.exports: $Exports<'react-native-status-bar-height'>;
}
