// flow-typed signature: 9b1e3c19f8ac3f7270149e999b22e1c6
// flow-typed version: <<STUB>>/react-native-udp_v^2.1.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-udp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-udp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-udp/UdpSocket' {
  declare module.exports: any;
}

declare module 'react-native-udp/UdpSockets' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-udp/UdpSocket.js' {
  declare module.exports: $Exports<'react-native-udp/UdpSocket'>;
}
declare module 'react-native-udp/UdpSockets.js' {
  declare module.exports: $Exports<'react-native-udp/UdpSockets'>;
}
