// flow-typed signature: 11d79ebf533294b7a462e03bd4558abb
// flow-typed version: <<STUB>>/react-native-camera_v^1.4.1/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-camera'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-camera' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-camera/commitlint.config' {
  declare module.exports: any;
}

declare module 'react-native-camera/src/Camera' {
  declare module.exports: any;
}

declare module 'react-native-camera/src/FaceDetector' {
  declare module.exports: any;
}

declare module 'react-native-camera/src/handlePermissions' {
  declare module.exports: any;
}

declare module 'react-native-camera/src/index' {
  declare module.exports: any;
}

declare module 'react-native-camera/src/RNCamera' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-camera/commitlint.config.js' {
  declare module.exports: $Exports<'react-native-camera/commitlint.config'>;
}
declare module 'react-native-camera/src/Camera.js' {
  declare module.exports: $Exports<'react-native-camera/src/Camera'>;
}
declare module 'react-native-camera/src/FaceDetector.js' {
  declare module.exports: $Exports<'react-native-camera/src/FaceDetector'>;
}
declare module 'react-native-camera/src/handlePermissions.js' {
  declare module.exports: $Exports<'react-native-camera/src/handlePermissions'>;
}
declare module 'react-native-camera/src/index.js' {
  declare module.exports: $Exports<'react-native-camera/src/index'>;
}
declare module 'react-native-camera/src/RNCamera.js' {
  declare module.exports: $Exports<'react-native-camera/src/RNCamera'>;
}
