// flow-typed signature: 348cbd1609d28945be90a04e420046f3
// flow-typed version: <<STUB>>/react-native-snap-carousel_v^3.7.5/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-snap-carousel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-snap-carousel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-snap-carousel/src/carousel/Carousel' {
  declare module.exports: any;
}

declare module 'react-native-snap-carousel/src/index' {
  declare module.exports: any;
}

declare module 'react-native-snap-carousel/src/pagination/Pagination' {
  declare module.exports: any;
}

declare module 'react-native-snap-carousel/src/pagination/Pagination.style' {
  declare module.exports: any;
}

declare module 'react-native-snap-carousel/src/pagination/PaginationDot' {
  declare module.exports: any;
}

declare module 'react-native-snap-carousel/src/parallaximage/ParallaxImage' {
  declare module.exports: any;
}

declare module 'react-native-snap-carousel/src/parallaximage/ParallaxImage.style' {
  declare module.exports: any;
}

declare module 'react-native-snap-carousel/src/utils/animations' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-snap-carousel/src/carousel/Carousel.js' {
  declare module.exports: $Exports<'react-native-snap-carousel/src/carousel/Carousel'>;
}
declare module 'react-native-snap-carousel/src/index.js' {
  declare module.exports: $Exports<'react-native-snap-carousel/src/index'>;
}
declare module 'react-native-snap-carousel/src/pagination/Pagination.js' {
  declare module.exports: $Exports<'react-native-snap-carousel/src/pagination/Pagination'>;
}
declare module 'react-native-snap-carousel/src/pagination/Pagination.style.js' {
  declare module.exports: $Exports<'react-native-snap-carousel/src/pagination/Pagination.style'>;
}
declare module 'react-native-snap-carousel/src/pagination/PaginationDot.js' {
  declare module.exports: $Exports<'react-native-snap-carousel/src/pagination/PaginationDot'>;
}
declare module 'react-native-snap-carousel/src/parallaximage/ParallaxImage.js' {
  declare module.exports: $Exports<'react-native-snap-carousel/src/parallaximage/ParallaxImage'>;
}
declare module 'react-native-snap-carousel/src/parallaximage/ParallaxImage.style.js' {
  declare module.exports: $Exports<'react-native-snap-carousel/src/parallaximage/ParallaxImage.style'>;
}
declare module 'react-native-snap-carousel/src/utils/animations.js' {
  declare module.exports: $Exports<'react-native-snap-carousel/src/utils/animations'>;
}
