// flow-typed signature: 0a8e9ac3d85fba1677a22822091815fe
// flow-typed version: <<STUB>>/react-native-randombytes_v^3.5.1/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-randombytes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-randombytes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'react-native-randombytes/index' {
  declare module.exports: $Exports<'react-native-randombytes'>;
}
declare module 'react-native-randombytes/index.js' {
  declare module.exports: $Exports<'react-native-randombytes'>;
}
