// flow-typed signature: 7ce525e0d9dd5376659954ca7e8e2480
// flow-typed version: <<STUB>>/stream-browserify_v^1.0.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stream-browserify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stream-browserify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stream-browserify/test/buf' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stream-browserify/index' {
  declare module.exports: $Exports<'stream-browserify'>;
}
declare module 'stream-browserify/index.js' {
  declare module.exports: $Exports<'stream-browserify'>;
}
declare module 'stream-browserify/test/buf.js' {
  declare module.exports: $Exports<'stream-browserify/test/buf'>;
}
