// flow-typed signature: fb32053666fdd3389e20a56d841771db
// flow-typed version: <<STUB>>/tweetnacl_vhttps://github.com/BrightID/tweetnacl-js/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tweetnacl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tweetnacl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tweetnacl/nacl-fast' {
  declare module.exports: any;
}

declare module 'tweetnacl/nacl-fast.min' {
  declare module.exports: any;
}

declare module 'tweetnacl/nacl' {
  declare module.exports: any;
}

declare module 'tweetnacl/nacl.min' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/00-api' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/01-verify.quick' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/02-randombytes.quick' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/03-onetimeauth.quick' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/04-secretbox' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/04-secretbox.quick' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/05-scalarmult' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/06-box' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/06-box.quick' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/07-hash' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/07-hash.quick' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/08-sign' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/08-sign.quick' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/benchmark/bench' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/benchmark/helpers' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/browser/init' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/c/00-secretbox' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/c/01-scalarmult' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/c/02-box' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/c/03-hash' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/c/04-sign' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/c/05-sign-keypair' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/data/base64.random' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/data/box.random' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/data/hash.random' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/data/hash.spec' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/data/onetimeauth.spec' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/data/scalarmult.random' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/data/secretbox.random' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/data/sign.spec' {
  declare module.exports: any;
}

declare module 'tweetnacl/test/timing/timing' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tweetnacl/nacl-fast.js' {
  declare module.exports: $Exports<'tweetnacl/nacl-fast'>;
}
declare module 'tweetnacl/nacl-fast.min.js' {
  declare module.exports: $Exports<'tweetnacl/nacl-fast.min'>;
}
declare module 'tweetnacl/nacl.js' {
  declare module.exports: $Exports<'tweetnacl/nacl'>;
}
declare module 'tweetnacl/nacl.min.js' {
  declare module.exports: $Exports<'tweetnacl/nacl.min'>;
}
declare module 'tweetnacl/test/00-api.js' {
  declare module.exports: $Exports<'tweetnacl/test/00-api'>;
}
declare module 'tweetnacl/test/01-verify.quick.js' {
  declare module.exports: $Exports<'tweetnacl/test/01-verify.quick'>;
}
declare module 'tweetnacl/test/02-randombytes.quick.js' {
  declare module.exports: $Exports<'tweetnacl/test/02-randombytes.quick'>;
}
declare module 'tweetnacl/test/03-onetimeauth.quick.js' {
  declare module.exports: $Exports<'tweetnacl/test/03-onetimeauth.quick'>;
}
declare module 'tweetnacl/test/04-secretbox.js' {
  declare module.exports: $Exports<'tweetnacl/test/04-secretbox'>;
}
declare module 'tweetnacl/test/04-secretbox.quick.js' {
  declare module.exports: $Exports<'tweetnacl/test/04-secretbox.quick'>;
}
declare module 'tweetnacl/test/05-scalarmult.js' {
  declare module.exports: $Exports<'tweetnacl/test/05-scalarmult'>;
}
declare module 'tweetnacl/test/06-box.js' {
  declare module.exports: $Exports<'tweetnacl/test/06-box'>;
}
declare module 'tweetnacl/test/06-box.quick.js' {
  declare module.exports: $Exports<'tweetnacl/test/06-box.quick'>;
}
declare module 'tweetnacl/test/07-hash.js' {
  declare module.exports: $Exports<'tweetnacl/test/07-hash'>;
}
declare module 'tweetnacl/test/07-hash.quick.js' {
  declare module.exports: $Exports<'tweetnacl/test/07-hash.quick'>;
}
declare module 'tweetnacl/test/08-sign.js' {
  declare module.exports: $Exports<'tweetnacl/test/08-sign'>;
}
declare module 'tweetnacl/test/08-sign.quick.js' {
  declare module.exports: $Exports<'tweetnacl/test/08-sign.quick'>;
}
declare module 'tweetnacl/test/benchmark/bench.js' {
  declare module.exports: $Exports<'tweetnacl/test/benchmark/bench'>;
}
declare module 'tweetnacl/test/benchmark/helpers.js' {
  declare module.exports: $Exports<'tweetnacl/test/benchmark/helpers'>;
}
declare module 'tweetnacl/test/browser/init.js' {
  declare module.exports: $Exports<'tweetnacl/test/browser/init'>;
}
declare module 'tweetnacl/test/c/00-secretbox.js' {
  declare module.exports: $Exports<'tweetnacl/test/c/00-secretbox'>;
}
declare module 'tweetnacl/test/c/01-scalarmult.js' {
  declare module.exports: $Exports<'tweetnacl/test/c/01-scalarmult'>;
}
declare module 'tweetnacl/test/c/02-box.js' {
  declare module.exports: $Exports<'tweetnacl/test/c/02-box'>;
}
declare module 'tweetnacl/test/c/03-hash.js' {
  declare module.exports: $Exports<'tweetnacl/test/c/03-hash'>;
}
declare module 'tweetnacl/test/c/04-sign.js' {
  declare module.exports: $Exports<'tweetnacl/test/c/04-sign'>;
}
declare module 'tweetnacl/test/c/05-sign-keypair.js' {
  declare module.exports: $Exports<'tweetnacl/test/c/05-sign-keypair'>;
}
declare module 'tweetnacl/test/data/base64.random.js' {
  declare module.exports: $Exports<'tweetnacl/test/data/base64.random'>;
}
declare module 'tweetnacl/test/data/box.random.js' {
  declare module.exports: $Exports<'tweetnacl/test/data/box.random'>;
}
declare module 'tweetnacl/test/data/hash.random.js' {
  declare module.exports: $Exports<'tweetnacl/test/data/hash.random'>;
}
declare module 'tweetnacl/test/data/hash.spec.js' {
  declare module.exports: $Exports<'tweetnacl/test/data/hash.spec'>;
}
declare module 'tweetnacl/test/data/onetimeauth.spec.js' {
  declare module.exports: $Exports<'tweetnacl/test/data/onetimeauth.spec'>;
}
declare module 'tweetnacl/test/data/scalarmult.random.js' {
  declare module.exports: $Exports<'tweetnacl/test/data/scalarmult.random'>;
}
declare module 'tweetnacl/test/data/secretbox.random.js' {
  declare module.exports: $Exports<'tweetnacl/test/data/secretbox.random'>;
}
declare module 'tweetnacl/test/data/sign.spec.js' {
  declare module.exports: $Exports<'tweetnacl/test/data/sign.spec'>;
}
declare module 'tweetnacl/test/timing/timing.js' {
  declare module.exports: $Exports<'tweetnacl/test/timing/timing'>;
}
