// flow-typed signature: 86c74839367001d3dd6d8d90e4e5b08c
// flow-typed version: <<STUB>>/url_v~0.10.1/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'url'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'url' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'url/test' {
  declare module.exports: any;
}

declare module 'url/url' {
  declare module.exports: any;
}

// Filename aliases
declare module 'url/test.js' {
  declare module.exports: $Exports<'url/test'>;
}
declare module 'url/url.js' {
  declare module.exports: $Exports<'url/url'>;
}
