// flow-typed signature: c4d170a5c1e90e4b11910849aed04aa0
// flow-typed version: <<STUB>>/@tradle/react-native-http_v^2.0.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@tradle/react-native-http'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@tradle/react-native-http' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@tradle/react-native-http/lib/request' {
  declare module.exports: any;
}

declare module '@tradle/react-native-http/lib/response' {
  declare module.exports: any;
}

// Filename aliases
declare module '@tradle/react-native-http/index' {
  declare module.exports: $Exports<'@tradle/react-native-http'>;
}
declare module '@tradle/react-native-http/index.js' {
  declare module.exports: $Exports<'@tradle/react-native-http'>;
}
declare module '@tradle/react-native-http/lib/request.js' {
  declare module.exports: $Exports<'@tradle/react-native-http/lib/request'>;
}
declare module '@tradle/react-native-http/lib/response.js' {
  declare module.exports: $Exports<'@tradle/react-native-http/lib/response'>;
}
