# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BrightID' do
  # this is very important to have!
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'react-native-randombytes', :path => '../node_modules/react-native-randombytes'

  pod 'react-native-spinkit', :path => '../node_modules/react-native-spinkit'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'


  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

end

# very important to have, unless you removed React dependencies for Libraries 
# and you rely on Cocoapods to manage it
post_install do |installer|
installer.pods_project.targets.each do |target|
  if target.name == "React"
    target.remove_from_project
  end
end
end