// flow-typed signature: b2a803c068f2a95bcc68fd0cfe272ced
// flow-typed version: <<STUB>>/console-browserify_v^1.1.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'console-browserify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'console-browserify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'console-browserify/test/index' {
  declare module.exports: any;
}

declare module 'console-browserify/test/static/test-adapter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'console-browserify/index' {
  declare module.exports: $Exports<'console-browserify'>;
}
declare module 'console-browserify/index.js' {
  declare module.exports: $Exports<'console-browserify'>;
}
declare module 'console-browserify/test/index.js' {
  declare module.exports: $Exports<'console-browserify/test/index'>;
}
declare module 'console-browserify/test/static/test-adapter.js' {
  declare module.exports: $Exports<'console-browserify/test/static/test-adapter'>;
}
