// flow-typed signature: 347c69e16a56e8715e3e7033b3adf088
// flow-typed version: <<STUB>>/constants-browserify_v^1.0.0/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'constants-browserify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'constants-browserify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'constants-browserify/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'constants-browserify/test.js' {
  declare module.exports: $Exports<'constants-browserify/test'>;
}
