// flow-typed signature: 96d059d659ee09eb1cffed4fd63a40cf
// flow-typed version: <<STUB>>/emittery_v^0.4.1/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'emittery'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'emittery' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'emittery/legacy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'emittery/index' {
  declare module.exports: $Exports<'emittery'>;
}
declare module 'emittery/index.js' {
  declare module.exports: $Exports<'emittery'>;
}
declare module 'emittery/legacy.js' {
  declare module.exports: $Exports<'emittery/legacy'>;
}
