// flow-typed signature: 0c1a83aaa40a0a277ab57af4b72838c3
// flow-typed version: <<STUB>>/react-native-tcp_v^3.2.1/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-tcp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-tcp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-tcp/base64-str' {
  declare module.exports: any;
}

declare module 'react-native-tcp/interfaces/interface' {
  declare module.exports: any;
}

declare module 'react-native-tcp/TcpServer' {
  declare module.exports: any;
}

declare module 'react-native-tcp/TcpSocket' {
  declare module.exports: any;
}

declare module 'react-native-tcp/TcpSockets' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-tcp/base64-str.js' {
  declare module.exports: $Exports<'react-native-tcp/base64-str'>;
}
declare module 'react-native-tcp/interfaces/interface.js' {
  declare module.exports: $Exports<'react-native-tcp/interfaces/interface'>;
}
declare module 'react-native-tcp/TcpServer.js' {
  declare module.exports: $Exports<'react-native-tcp/TcpServer'>;
}
declare module 'react-native-tcp/TcpSocket.js' {
  declare module.exports: $Exports<'react-native-tcp/TcpSocket'>;
}
declare module 'react-native-tcp/TcpSockets.js' {
  declare module.exports: $Exports<'react-native-tcp/TcpSockets'>;
}
