sequenceDiagram

    %% Sequence of interconnecting a group
    %% Preconditions:
    %%  - Bob has a queue of pending group connections to establish
    %%  - Bob has uploaded his profile to the group channel

    autonumber
	participant B as One participant ("Bob")
    participant P as ProfileService
    participant N as NodeAPI
	participant O as Other participant ("Candidate")

    loop for each candidate in pending connections queue
        B->>B: confirm connection
        alt Bob is initiating
            B->>B: sign partly connection message
            B->>O: provide profileID + signed Message via push notification
            B--xN: start polling for "Add connection" operation
            activate O
            O->>P: request profile "Bob" from group channel
            activate P
            P->>O: provide profile "Bob"
            deactivate P
            O->>O: Add Bob to pending connections queue
        else Bob is responding
            B->>B: sign full connection message
            B->>N: Submit "Add Connection Alice+Bob" operation
            B--xN: start polling for "Add connection" operation
        end

        B->>B: locally store connection to candidate ("initiated" state)
        B->>B: remove candidate from pending connections queue

    end

