sequenceDiagram

    %% Sequence of creating a 1:1 connection
    %% Does not rely on profile channels, instead directly uses profileID to retrieve profile

    autonumber
	participant A as Alice
    participant P as ProfileService
    participant N as NodeAPI
    participant B as Bob
    A->>A: create AESKey, notificationToken, profileID
    A->>A: create QRCode
	A->>P: upload profile "Alice" with notificationToken
    B->>+A: scan QRCode
    A->>-B: AESkey, profileID
    B->>+P: request profile "Alice" via profileID
    P->>B: provide profile "Alice"
    activate B
    B->>B: Request user confirmation
    Note over B: Locally add connection in waiting state, start polling "Add Connection" operation.
    B->>B: Generate profileID
    B->>B: Encrypt profile with AESKey
    deactivate B
    B->>P: Upload profile "Bob"
    B->>A: provide profileID + signedMessage via pushnotification
	A->>+P: request profile "Bob" via profileID from notification
    P->>-A: provide profile "Bob"
    A->>A: Request user confirmation
    Note over A: Locally add connection in waiting state, start polling "Add Connection" operation.
    A-xN: Submit "Add Connection Alice+Bob" operation
    activate N
    N->N: wait for tx confirmation
    deactivate N
    N->>A: provide op result (via polling)
    N->>B: provide op result (via polling)
