sequenceDiagram

    %% Sequence of interconnecting a group
    %% Profiles are shared through a channel on Profile Server

    autonumber
	participant A as Group Connection Initiator
    participant P as ProfileService
    participant N as NodeAPI
    participant B as all meeting participants
    A->>A: create AESKey, profileID, channelID, notificationToken
    A->>A: create QRCode
	    A->>P: upload profile with notificationToken
    B->>A: scan QRCode
    activate A
    A->>B: AESkey, channelID
    deactivate A
    activate B
    B->>B: Generate own profileID, notifikationToken
    deactivate B
    B->>P: Upload own profile with notificationToken to channel
    B->>+P: request list of profileIDs in channel
    P->>-B: list of profileIDs
    loop for each profileID
        B->>+P: request profile from channel
        P->>-B: profile
        B->>B: Add candidate to pending connections queue
    end
