name: Build iOS
on: [push, pull_request]

jobs:

  build_debug_ipa:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: BrightID
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn install
          echo "::add-path::/home/runner/work/BrightID/BrightID/BrightID/node_modules/.bin"
      - name: Install pod dependencies
        run: |
          cd ios && pod install && cd ..
      - name: debug build
        run: |
          echo "TODO: Insert iOS Debug build instructions here :-)"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: brightId-debug.ipa
          path: /home/runner/work/BrightID/BrightID/BrightID/ios/path/to/brightID-debug.ipa

  build_release_ipa:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: BrightID
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn install
          echo "::add-path::/home/runner/work/BrightID/BrightID/BrightID/node_modules/.bin"
      - name: Install pod dependencies
        run: |
          cd ios && pod install && cd ..
      - name: release build
        run: |
          echo "TODO: Insert iOS Release build instructions here :-)"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: brightId-release.ipa
          path: /home/runner/work/BrightID/BrightID/BrightID/ios/path/to/brightID-release.ipa
