name: Build Android
on:
  push:

jobs:
  build debug:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: BrightID
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          yarn install
      - name: build
        run: |
          sh ./scripts/build_debug.sh
      - name: Upload Artifact
          uses: actions/upload-artifact@v1
          with:
            name: app-debug.apk
            path: android/app/build/outputs/apk/debug/
